Add installer check job for latest in cd_dev

diff --git a/.github/workflows/cd_dev.yaml b/.github/workflows/cd_dev.yaml
--- a/.github/workflows/cd_dev.yaml
+++ b/.github/workflows/cd_dev.yaml
@@ -18,6 +18,15 @@ on:
     branches: [master]
     types: [completed]
   workflow_dispatch:
+    inputs:
+      alt_version:
+        required: false
+        description: Provide expected semver for `installer_check` job. If empty `VERSION+<git commit>` in repo will be used
+        default: ''
+
+env:
+  USE_VERSION: ${{ github.event.inputs.alt_version }}
+
 
 jobs:
   # test fluvio in local cluster 
@@ -140,6 +149,44 @@ jobs:
           fields: repo,message,commit,author,action,eventName,ref,workflow,job,took # selectable (default: repo,message)
         env:
           SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
+
+  # Verify latest version of CLI
+  installer_check:
+    name: Installer check
+    runs-on: ${{ matrix.os }}
+    strategy:
+      matrix:
+        version: [latest]
+    steps:
+      - uses: actions/checkout@v2
+      - name: Set the expected fluvio version
+        run: |
+          if [[ -z "${{ env.USE_VERSION }}" ]]; then
+            echo "EXPECTED_VERSION=$(cat VERSION)+$(git rev-parse HEAD)" | tee -a $GITHUB_ENV
+          else
+            echo "EXPECTED_VERSION=${{ github.event.inputs.alt_version }}" | tee -a $GITHUB_ENV
+          fi
+          echo "EXPECTED_VERSION: $EXPECTED_VERSION"
+
+      - name: Curl Install - latest 
+        if: matrix.version == 'latest'
+        run: echo "VERSION=latest" | tee -a $GITHUB_ENV
+
+        # Utilizes the env var set in the previous step 
+      - name: Curl Install
+        run: curl -fsS https://packages.fluvio.io/v1/install.sh | bash | tee /tmp/installer.version
+
+      - name: Verify installer output
+        run: |
+            INSTALLER_VERSION=$(cat /tmp/installer.version | grep "Downloading Fluvio" | awk '{print $5}')
+            if [ "$INSTALLER_VERSION" = "$EXPECTED_VERSION" ]; then
+              echo "✅ Installer version check passed: $EXPECTED_VERSION";
+            else
+              echo "❌ Installer version check failed";
+              echo "Version reported by installer: $INSTALLER_VERSION";
+              echo "Expected version: $EXPECTED_VERSION";
+              exit 1;
+            fi
 
   cli-platform-cross-version-test:
     name: CLI (${{ matrix.cli_version }}) x Platform (${{ matrix.cluster_version }}) version test 
