add diagnostics to cd_release (#2102)
* add diagnostics steps to help debug `cd-release` workflow.
* show the log file path in CLI diagnostics

diff --git a/.github/workflows/cd_release.yml b/.github/workflows/cd_release.yml
--- a/.github/workflows/cd_release.yml
+++ b/.github/workflows/cd_release.yml
@@ -4,7 +4,8 @@ permissions:
   contents: read
 
 on:
-
+#  pull_request:
+#    branches: [master]
   workflow_run:
     workflows: ["Release"]
     types:
@@ -14,7 +15,7 @@ on:
       alt_version:
         required: false
         description: Provide expected semver. If empty VERSION in repo will be used
-        default: ''
+        default: ""
 
 env:
   USE_VERSION: ${{ github.event.inputs.alt_version }}
@@ -42,28 +43,28 @@ jobs:
       - name: Set the VERSION env var for installer script
         if: matrix.version == 'none'
         run: echo "Leave VERSION unset"
-      - name: Curl Install - stable 
+      - name: Curl Install - stable
         if: matrix.version == 'stable'
         run: echo "VERSION=stable" | tee -a $GITHUB_ENV
       - name: Curl Install - Version number
         if: matrix.version == 'semver'
         run: echo "VERSION=$EXPECTED_VERSION" | tee -a $GITHUB_ENV
 
-        # Utilizes the env var set in the previous step 
+        # Utilizes the env var set in the previous step
       - name: Curl Install
         run: curl -fsS https://packages.fluvio.io/v1/install.sh | bash | tee /tmp/installer.version
 
       - name: Verify installer output
         run: |
-            INSTALLER_VERSION=$(cat /tmp/installer.version | grep "Downloading Fluvio" | grep -v "channel" | awk '{print $5}')
-            if [ "$INSTALLER_VERSION" = "$EXPECTED_VERSION" ]; then
-              echo "✅ Installer version check passed: $EXPECTED_VERSION";
-            else
-              echo "❌ Installer version check failed";
-              echo "Version reported by installer: $INSTALLER_VERSION";
-              echo "Expected version: $EXPECTED_VERSION";
-              exit 1;
-            fi
+          INSTALLER_VERSION=$(cat /tmp/installer.version | grep "Downloading Fluvio" | grep -v "channel" | awk '{print $5}')
+          if [ "$INSTALLER_VERSION" = "$EXPECTED_VERSION" ]; then
+            echo "✅ Installer version check passed: $EXPECTED_VERSION";
+          else
+            echo "❌ Installer version check failed";
+            echo "Version reported by installer: $INSTALLER_VERSION";
+            echo "Expected version: $EXPECTED_VERSION";
+            exit 1;
+          fi
 
   start_cluster:
     name: Start cluster test
@@ -83,17 +84,32 @@ jobs:
         run: |
           ./k8-util/cluster/reset-k3d.sh
       - name: Install Fluvio
-        run: curl -fsS https://packages.fluvio.io/v1/install.sh | bash
-
+        run: |
+          curl -fsS https://packages.fluvio.io/v1/install.sh | bash
+          echo "$HOME/.fluvio/bin" >> $GITHUB_PATH
       - name: Pre-Start - local cluster
         if: matrix.cluster_type == 'local'
         run: echo "IF_LOCAL=--local" | tee -a $GITHUB_ENV
       - name: Pre-Start - Kubernetes cluster
         if: matrix.cluster_type == 'k8s'
         run: echo "IF_LOCAL=" | tee -a $GITHUB_ENV
- 
       - name: Start cluster
-        run: ~/.fluvio/bin/fluvio cluster start ${IF_LOCAL} 
+        timeout-minutes: 3
+        run: |
+          fluvio version
+          fluvio cluster start ${IF_LOCAL}
+      - name: Run diagnostics
+        if: failure()
+        timeout-minutes: 5
+        run: |
+          fluvio cluster diagnostics
+      - name: Upload diagnostics
+        uses: actions/upload-artifact@v2
+        timeout-minutes: 5
+        if: ${{ !success() }}
+        with:
+          name: start_cluster_${{ matrix.cluster_type }}
+          path: diagnostics*.gz
       # TODO: Verify platform version
 
   upgrade_prev_stable:
