more debugging

diff --git a/.github/workflows/cd_release.yml b/.github/workflows/cd_release.yml
--- a/.github/workflows/cd_release.yml
+++ b/.github/workflows/cd_release.yml
@@ -15,7 +15,7 @@ on:
       alt_version:
         required: false
         description: Provide expected semver. If empty VERSION in repo will be used
-        default: ''
+        default: ""
 
 env:
   USE_VERSION: ${{ github.event.inputs.alt_version }}
@@ -43,28 +43,28 @@ jobs:
       - name: Set the VERSION env var for installer script
         if: matrix.version == 'none'
         run: echo "Leave VERSION unset"
-      - name: Curl Install - stable 
+      - name: Curl Install - stable
         if: matrix.version == 'stable'
         run: echo "VERSION=stable" | tee -a $GITHUB_ENV
       - name: Curl Install - Version number
         if: matrix.version == 'semver'
         run: echo "VERSION=$EXPECTED_VERSION" | tee -a $GITHUB_ENV
 
-        # Utilizes the env var set in the previous step 
+        # Utilizes the env var set in the previous step
       - name: Curl Install
         run: curl -fsS https://packages.fluvio.io/v1/install.sh | bash | tee /tmp/installer.version
 
       - name: Verify installer output
         run: |
-            INSTALLER_VERSION=$(cat /tmp/installer.version | grep "Downloading Fluvio" | grep -v "channel" | awk '{print $5}')
-            if [ "$INSTALLER_VERSION" = "$EXPECTED_VERSION" ]; then
-              echo "✅ Installer version check passed: $EXPECTED_VERSION";
-            else
-              echo "❌ Installer version check failed";
-              echo "Version reported by installer: $INSTALLER_VERSION";
-              echo "Expected version: $EXPECTED_VERSION";
-              exit 1;
-            fi
+          INSTALLER_VERSION=$(cat /tmp/installer.version | grep "Downloading Fluvio" | grep -v "channel" | awk '{print $5}')
+          if [ "$INSTALLER_VERSION" = "$EXPECTED_VERSION" ]; then
+            echo "✅ Installer version check passed: $EXPECTED_VERSION";
+          else
+            echo "❌ Installer version check failed";
+            echo "Version reported by installer: $INSTALLER_VERSION";
+            echo "Expected version: $EXPECTED_VERSION";
+            exit 1;
+          fi
 
   start_cluster:
     name: Start cluster test
@@ -95,13 +95,14 @@ jobs:
         run: echo "IF_LOCAL=" | tee -a $GITHUB_ENV
       - name: Start cluster
         timeout-minutes: 3
-        run: fluvio cluster start ${IF_LOCAL} 
+        run: fluvio cluster start ${IF_LOCAL}
       - name: Run diagnostics
         if: failure()
         timeout-minutes: 5
         run: |
           ls /tmp
           ps -ef | grep fluvio
+          cat /tmp/flv_sc.log
           fluvio cluster diagnostics
       - name: Upload diagnostics
         uses: actions/upload-artifact@v2
