Add Fluvio-test self check

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1066,3 +1066,106 @@ jobs:
     steps:
       - name: Done
         run: echo "Done!"
+
+  shell_job_test:
+    name: Test if this job reports as cancelled 
+    runs-on: ${{ matrix.os }}
+    strategy:
+      matrix:
+        os: [ubuntu-latest]
+    steps:
+      - name:
+        run: exit 143
+
+  # TODO: Change signal to SIGINT, add job that always fails and use fluvio test binary after starting cluster
+  fluvio_test_panic:
+    name: fluvio-test panic
+    runs-on: ${{ matrix.os }}
+    needs:
+      - build_primary_binaries
+      - config
+    env:
+      UNINSTALL: noclean
+      FLUVIO_BIN: ~/bin/fluvio
+      TEST_BIN: ~/bin/fluvio-test
+    strategy:
+      fail-fast: false
+      matrix:
+        os: [ubuntu-latest]
+        rust-target: [x86_64-unknown-linux-musl]
+        run: [r1]
+        spu: [2]
+        test:
+          [
+            self_test,
+          ]
+    steps:
+      - uses: actions/checkout@v2
+      - name: Download artifact - fluvio
+        uses: actions/download-artifact@v2
+        with:
+          name: fluvio-${{ matrix.rust-target }}
+          path: ~/bin
+      - name: Download artifact - fluvio-run
+        uses: actions/download-artifact@v2
+        with:
+          name: fluvio-run-${{ matrix.rust-target }}
+          path: ~/.fluvio/extensions
+      - name: Download artifact - fluvio-test
+        uses: actions/download-artifact@v2
+        with:
+          name: fluvio-test-${{ matrix.rust-target }}
+          path: ~/bin
+      - name: Mark executable
+        run: |
+          chmod +x ~/bin/fluvio ~/bin/fluvio-test ~/.fluvio/extensions/fluvio-run
+          echo "~/bin" >> $GITHUB_PATH
+      #- name: Print version
+      #  run: fluvio version
+      #- name: Set up cluster
+      #  run: |
+      #    curl -s https://raw.githubusercontent.com/rancher/k3d/main/install.sh | TAG=${{ env.K3D_VERSION }} bash
+      #    ./k8-util/cluster/reset-k3d.sh
+      #- name: Start fluvio cluster
+      #  timeout-minutes: 5
+      #  run: fluvio cluster start --local --develop --spu ${{ matrix.spu }} --rust-log fluvio=debug
+      #- name: sleep
+      #  run: sleep 15
+      - name: Run Fluvio Test Self Check 
+        timeout-minutes: 5
+        run: |
+          ./fluvio-test self_check -- --force-panic  
+      - name: Save logs
+        if: ${{ !success() }}
+        run: |
+          date
+          uname -a
+          helm list
+          kubectl get spu
+          kubectl get statefulset
+          kubectl get topics
+          kubectl get partitions
+          ps -ef | grep fluvio
+
+      - name: Upload SC Logs
+        uses: actions/upload-artifact@v2
+        timeout-minutes: 5
+        if: ${{ !success() }}
+        with:
+          name: local-${{ matrix.run }}-${{ matrix.test }}-sc-log
+          path: /tmp/flv_sc.log
+      - name: Upload SPU 1 Log
+        uses: actions/upload-artifact@v2
+        timeout-minutes: 5
+        if: ${{ !success() }}
+        with:
+          name: local-${{ matrix.run }}-${{ matrix.test }}-spu1-logs
+          path: /tmp/spu_log_5001.log
+      - name: Upload SPU 2 Log
+        uses: actions/upload-artifact@v2
+        timeout-minutes: 5
+        if: ${{ !success() }}
+        with:
+          name: local-${{ matrix.run }}-${{ matrix.test }}-spu1-logs
+          path: /tmp/spu_log_5002.log
+
