Try trapping signal via makefile

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1067,38 +1067,37 @@ jobs:
       - name: Done
         run: echo "Done!"
 
-  shell_job_sigint_test:
-    name: SIGINT Test if this job reports as cancelled 
-    runs-on: ${{ matrix.os }}
-    strategy:
-      fail-fast: false
-      matrix:
-        os: [ubuntu-latest]
-        run: [r1, r2, r3, r4, r5]
-    steps:
-      - name:
-        run: |
-          trap '' SIGINT
-          kill -SIGINT $$
-          trap - SIGINT
-          exit 1
+  #shell_job_sigint_test:
+  #  name: SIGINT Test if this job reports as cancelled 
+  #  runs-on: ${{ matrix.os }}
+  #  strategy:
+  #    fail-fast: false
+  #    matrix:
+  #      os: [ubuntu-latest]
+  #      run: [r1, r2, r3, r4, r5]
+  #  steps:
+  #    - name:
+  #      run: |
+  #        trap '' SIGINT
+  #        kill -SIGINT $$
+  #        trap - SIGINT
+  #        exit 1
 
-
-  shell_job_sigterm_test:
-    name: SIGTERM Test if this job reports as cancelled 
-    runs-on: ${{ matrix.os }}
-    strategy:
-      fail-fast: false
-      matrix:
-        os: [ubuntu-latest]
-        run: [r1, r2, r3, r4, r5]
-    steps:
-      - name:
-        run: |
-          trap '' SIGTERM
-          kill -SIGTERM $$
-          trap - SIGTERM
-          exit 1
+  #shell_job_sigterm_test:
+  #  name: SIGTERM Test if this job reports as cancelled 
+  #  runs-on: ${{ matrix.os }}
+  #  strategy:
+  #    fail-fast: false
+  #    matrix:
+  #      os: [ubuntu-latest]
+  #      run: [r1, r2, r3, r4, r5]
+  #  steps:
+  #    - name:
+  #      run: |
+  #        trap '' SIGTERM
+  #        kill -SIGTERM $$
+  #        trap - SIGTERM
+  #        exit 1
 
   fluvio_test_panic_fail:
     name: fluvio-test panic
@@ -1115,7 +1114,7 @@ jobs:
       matrix:
         os: [ubuntu-latest]
         rust-target: [x86_64-unknown-linux-musl]
-        run: [r1, r2, r3, r4, r5]
+        run: [r1, r2]
         spu: [2]
         test:
           [
@@ -1194,7 +1193,7 @@ jobs:
           path: /tmp/spu_log_5002.log
 
   fluvio_test_panic_pass:
-    name: fluvio-test panic
+    name: fluvio-test pass 
     runs-on: ${{ matrix.os }}
     needs:
       - build_primary_binaries
@@ -1208,7 +1207,7 @@ jobs:
       matrix:
         os: [ubuntu-latest]
         rust-target: [x86_64-unknown-linux-musl]
-        run: [r1, r2, r3, r4, r5]
+        run: [r1, r2]
         spu: [2]
         test:
           [
@@ -1246,7 +1245,7 @@ jobs:
       #  run: fluvio cluster start --local --develop --spu ${{ matrix.spu }} --rust-log fluvio=debug
       #- name: sleep
       #  run: sleep 15
-      - name: Run Fluvio Test Self Check - Panic 
+      - name: Run Fluvio Test Self Check
         timeout-minutes: 5
         run: |
           trap '' SIGTERM
@@ -1286,3 +1285,95 @@ jobs:
           name: local-${{ matrix.run }}-${{ matrix.test }}-spu1-logs
           path: /tmp/spu_log_5002.log
 
+  fluvio_test_panic_makefile:
+    name: fluvio-test makefile 
+    runs-on: ${{ matrix.os }}
+    needs:
+      - build_primary_binaries
+      - config
+    env:
+      UNINSTALL: noclean
+      FLUVIO_BIN: ~/bin/fluvio
+      TEST_BIN: ~/bin/fluvio-test
+    strategy:
+      fail-fast: false
+      matrix:
+        os: [ubuntu-latest]
+        rust-target: [x86_64-unknown-linux-musl]
+        run: [r1, r2]
+        spu: [2]
+        test:
+          [
+            self_test,
+          ]
+    steps:
+      - uses: actions/checkout@v2
+      - name: Download artifact - fluvio
+        uses: actions/download-artifact@v2
+        with:
+          name: fluvio-${{ matrix.rust-target }}
+          path: ~/bin
+      - name: Download artifact - fluvio-run
+        uses: actions/download-artifact@v2
+        with:
+          name: fluvio-run-${{ matrix.rust-target }}
+          path: ~/.fluvio/extensions
+      - name: Download artifact - fluvio-test
+        uses: actions/download-artifact@v2
+        with:
+          name: fluvio-test-${{ matrix.rust-target }}
+          path: ~/bin
+      - name: Mark executable
+        run: |
+          chmod +x ~/bin/fluvio ~/bin/fluvio-test ~/.fluvio/extensions/fluvio-run
+          echo "~/bin" >> $GITHUB_PATH
+      #- name: Print version
+      #  run: fluvio version
+      #- name: Set up cluster
+      #  run: |
+      #    curl -s https://raw.githubusercontent.com/rancher/k3d/main/install.sh | TAG=${{ env.K3D_VERSION }} bash
+      #    ./k8-util/cluster/reset-k3d.sh
+      #- name: Start fluvio cluster
+      #  timeout-minutes: 5
+      #  run: fluvio cluster start --local --develop --spu ${{ matrix.spu }} --rust-log fluvio=debug
+      #- name: sleep
+      #  run: sleep 15
+      - name: Run Fluvio Test Self Check
+        timeout-minutes: 5
+        run: |
+          trap '' SIGTERM
+          make fluvio-test-self-check
+          trap - SIGTERM
+      - name: Save logs
+        if: ${{ !success() }}
+        run: |
+          date
+          uname -a
+          helm list
+          kubectl get spu
+          kubectl get statefulset
+          kubectl get topics
+          kubectl get partitions
+          ps -ef | grep fluvio
+
+      - name: Upload SC Logs
+        uses: actions/upload-artifact@v2
+        timeout-minutes: 5
+        if: ${{ !success() }}
+        with:
+          name: local-${{ matrix.run }}-${{ matrix.test }}-sc-log
+          path: /tmp/flv_sc.log
+      - name: Upload SPU 1 Log
+        uses: actions/upload-artifact@v2
+        timeout-minutes: 5
+        if: ${{ !success() }}
+        with:
+          name: local-${{ matrix.run }}-${{ matrix.test }}-spu1-logs
+          path: /tmp/spu_log_5001.log
+      - name: Upload SPU 2 Log
+        uses: actions/upload-artifact@v2
+        timeout-minutes: 5
+        if: ${{ !success() }}
+        with:
+          name: local-${{ matrix.run }}-${{ matrix.test }}-spu1-logs
+          path: /tmp/spu_log_5002.log
